title: sachidanand.github.io
description: Robotics portfolio – motion planning, autonomous navigation, manipulation
theme: minima
baseurl: "/sachidanand.github.io"
url: "https://halhalli-s.github.io"
